### PR TITLE
add test for percent decoding

### LINKED ISSUE #64: Parameters should be percent escaped
In Vapor 2 the following code:
```swift
get("hello", ":id") { req in
            let id = req.parameters["id"]?.string

            var json = JSON()
            try json.set("hello", id)
            return json
        }
```

Would produce the following output:

- GET /hello/abc1234 `{"hello":"abc1234"}`
- GET /hello/abc|1234 `{"hello":"abc|1234"}`
- GET /hello/abc%7C1234 `{"hello":"abc|1234"}`

In Vapor 3 instead:

- GET /hello/abc1234 `{"hello":"abc1234"}`
- GET /hello/abc|1234 `{"hello":"abc%7C1234"}` // Notice that this is automatically encoded by any client before sending
- GET /hello/abc%7C1234 `{"hello":"abc%7C1234"}`

This to me seems like a regression.

The code that was taking care of this can be found on `Router.swift` on tag `2.2.1`.
```swift
public func slugs(for path: [String]) -> Parameters {
        var slugs: [String: Parameters] = [:]
        slugIndexes.forEach { key, index in
            guard let val = path[safe: index]
                .flatMap({ $0.removingPercentEncoding })
                .flatMap({ Parameters.string($0) })
                else { return }

            if let existing = slugs[key] {
                var array = existing.array ?? [existing]
                array.append(val)
                slugs[key] = .array(array)
            } else {
                slugs[key] = val
            }
        }
        return .object(slugs)
    }
```

### PR DESCRIPTION
**Pull request by tanner0101**
fixes #64

### CODE REVIEW

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by tanner0101** [comment]
@vapor-bot test performance

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1107 coins.

**Pull request merged**
