### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by grundoon**
update chat badge to Discord

### CODE REVIEW

**Comment by twof** [comment]
Approved by accident, but I'm closing this one out since vapor.team correctly routes to discord now

**Comment by grundoon** [comment]
It's not about the routing so much as the badge display (which is broken). 😃

**Comment by twof** [comment]
Oh totally missed that. My bad

**Comment by penny-coin** [comment]
Hey @grundoon, you just merged a pull request, have a coin! 

You now have 98 coins.

**Pull request merged**
