### PR TITLE
remove constant value from node in radix tree

### PR DESCRIPTION
**Pull request by tanner0101**
This removes `TrieRouter.Node.value` to reduce memory footprint of `TrieRouter`.

### CODE REVIEW

**Comment by tanner0101** [comment]
I've also added a new `linux-performance` workflow to this repo and some expected perf numbers for Linux. This isn't a perfect solution, since we're relying on Circle CI to provide consistent performance. But this is worth testing out as it might help us catch regressions.

**Comment by tanner0101** [comment]
FWIW, the performance seems consistent so far:

```
[PERFORMANCE] testCaseSensitivePerformance() expected: 0.024 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:120: Test Case 'RouterTests.testCaseSensitivePerformance' measured [Time, seconds] average: 0.025, relative standard deviation: 6.406%, values: [0.026066, 0.025866, 0.023669, 0.023533, 0.023543, 0.023424, 0.027948, 0.024180, 0.023441, 0.023467], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
Test Case 'RouterTests.testCaseSensitivePerformance' passed (0.246 seconds)
Test Case 'RouterTests.testCaseInsensitivePerformance' started at 2019-02-14 17:31:18.068

[PERFORMANCE] testCaseInsensitivePerformance() expected: 0.032 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:138: Test Case 'RouterTests.testCaseInsensitivePerformance' measured [Time, seconds] average: 0.033, relative standard deviation: 1.373%, values: [0.032589, 0.032301, 0.032533, 0.032449, 0.032416, 0.032363, 0.033790, 0.032282, 0.032348, 0.032407], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
Test Case 'RouterTests.testCaseInsensitivePerformance' passed (0.326 seconds)
Test Case 'RouterTests.testCaseInsensitiveRoutingMatchFirstPerformance' started at 2019-02-14 17:31:18.394

[PERFORMANCE] testCaseInsensitiveRoutingMatchFirstPerformance() expected: 0.045 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:156: Test Case 'RouterTests.testCaseInsensitiveRoutingMatchFirstPerformance' measured [Time, seconds] average: 0.046, relative standard deviation: 4.267%, values: [0.045450, 0.050519, 0.049604, 0.045537, 0.045357, 0.045586, 0.045428, 0.045206, 0.045356, 0.045333], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
Test Case 'RouterTests.testCaseInsensitiveRoutingMatchFirstPerformance' passed (0.464 seconds)
Test Case 'RouterTests.testCaseInsensitiveRoutingMatchLastPerformance' started at 2019-02-14 17:31:18.857

[PERFORMANCE] testCaseInsensitiveRoutingMatchLastPerformance() expected: 0.046 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:174: Test Case 'RouterTests.testCaseInsensitiveRoutingMatchLastPerformance' measured [Time, seconds] average: 0.045, relative standard deviation: 0.309%, values: [0.044925, 0.045076, 0.044981, 0.044896, 0.044884, 0.045306, 0.045004, 0.044988, 0.044795, 0.045051], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
Test Case 'RouterTests.testCaseInsensitiveRoutingMatchLastPerformance' passed (0.45 seconds)
Test Case 'RouterTests.testMinimalRouterCaseInsensitivePerformance' started at 2019-02-14 17:31:19.307

[PERFORMANCE] testMinimalRouterCaseInsensitivePerformance() expected: 0.016 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:208: Test Case 'RouterTests.testMinimalRouterCaseInsensitivePerformance' measured [Time, seconds] average: 0.016, relative standard deviation: 0.315%, values: [0.015920, 0.015784, 0.015795, 0.015870, 0.015879, 0.015845, 0.015850, 0.015878, 0.015776, 0.015788], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
Test Case 'RouterTests.testMinimalRouterCaseInsensitivePerformance' passed (0.159 seconds)
Test Case 'RouterTests.testMinimalRouterCaseSensitivePerformance' started at 2019-02-14 17:31:19.466

[PERFORMANCE] testMinimalRouterCaseSensitivePerformance() expected: 0.021 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:191: Test Case 'RouterTests.testMinimalRouterCaseSensitivePerformance' measured [Time, seconds] average: 0.020, relative standard deviation: 0.138%, values: [0.019901, 0.019881, 0.019868, 0.019859, 0.019850, 0.019930, 0.019895, 0.019860, 0.019848, 0.019847], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
Test Case 'RouterTests.testMinimalRouterCaseSensitivePerformance' passed (0.199 seconds)
Test Case 'RouterTests.testMinimalEarlyFailPerformance' started at 2019-02-14 17:31:19.665

[PERFORMANCE] testMinimalEarlyFailPerformance() expected: 0.013 seconds
/root/project/Tests/RoutingKitTests/RouterTests.swift:226: Test Case 'RouterTests.testMinimalEarlyFailPerformance' measured [Time, seconds] average: 0.013, relative standard deviation: 0.155%, values: [0.012814, 0.012846, 0.012819, 0.012787, 0.012807, 0.012790, 0.012790, 0.012791, 0.012800, 0.012830], performanceMetricID:org.swift.XCTPerformanceMetric_WallClockTime, maxPercentRelativeStandardDeviation: 10.000%, maxStandardDeviation: 0.100
```

**Comment by twof** [comment]
Were there any performance changes from this change?

**Comment by tanner0101** [comment]
@twof even if this doesn't have any performance gains (it will _at least_ remain the same there). It does cut the memory usage of router in half which could make a noticeable difference in real-world applications.

**Comment by twof** [comment]
@tanner0101 ahh in that case +1. Merge this and then I'll merge the other one if we're good there.

**Comment by penny-coin** [comment]
Hey @tanner0101, you just merged a pull request, have a coin! 

You now have 1080 coins.

**Pull request merged**
